# Generated by Django 5.0.1 on 2025-12-21 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SB1010',
            fields=[
                ('b1_cod', models.CharField(db_column='B1_COD', max_length=30, primary_key=True, serialize=False)),
                ('b1_desc', models.CharField(db_column='B1_DESC', max_length=100)),
                ('b1_desenho', models.CharField(db_column='B1_DESENHO', max_length=50)),
                ('deleted', models.CharField(db_column='D_E_L_E_T_', max_length=1)),
            ],
            options={
                'db_table': 'sb1010',
                'managed': False,
            },
        ),
    ]
