# Generated by Django 5.0.1 on 2025-12-22 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_sb1010'),
        ('drawings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Catálogo de Produtos'},
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={'ordering': ['name'], 'verbose_name': 'Tipo de Produto', 'verbose_name_plural': 'Tipos de Produtos'},
        ),
        migrations.AlterModelOptions(
            name='sb1010',
            options={'managed': False, 'verbose_name': 'Produto Protheus', 'verbose_name_plural': 'Produtos Protheus (SB1010)'},
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'ordering': ['name'], 'verbose_name': 'Setor', 'verbose_name_plural': 'Setores'},
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.producttype', verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.sector', verbose_name='Setor'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('drawing', 'sector', 'product_type')},
        ),
    ]
