# Generated by Django 5.0.1 on 2025-12-21 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='Número da Ordem')),
                ('status', models.CharField(choices=[('PLANNED', 'Planejado'), ('IN_PRODUCTION', 'Em Produção'), ('FINISHED', 'Finalizado'), ('ON_HOLD', 'Em Espera'), ('CANCELED', 'Cancelado')], default='PLANNED', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Ordem de Produção',
                'verbose_name_plural': 'Ordens de Produção',
            },
        ),
    ]
