# Generated by Django 5.0.1 on 2025-12-25 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_alter_product_options_alter_producttype_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Código de Rastreio')),
                ('quantity', models.IntegerField(verbose_name='Quantidade')),
                ('location', models.CharField(max_length=100, verbose_name='Localização Atual')),
                ('responsible_person', models.CharField(max_length=100, verbose_name='Responsável Atual')),
                ('movement_history', models.JSONField(blank=True, default=list, verbose_name='Histórico de Movimentações')),
                ('action_type', models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Saída')], default='IN', max_length=3, verbose_name='Tipo de Ação')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_entries', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que registrou')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_movements', to='catalog.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Controle Físico',
                'verbose_name_plural': 'Controles Físicos',
                'ordering': ['-created_at'],
            },
        ),
    ]
