# Generated by Django 5.0.1 on 2025-12-25 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_options_alter_producttype_options_and_more'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='physicalcontrol',
            options={},
        ),
        migrations.RemoveField(
            model_name='physicalcontrol',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='physicalcontrol',
            name='client_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código do Cliente'),
        ),
        migrations.AddField(
            model_name='physicalcontrol',
            name='client_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Cliente'),
        ),
        migrations.AddField(
            model_name='physicalcontrol',
            name='nf_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número da NF'),
        ),
        migrations.AddField(
            model_name='physicalcontrol',
            name='sender',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Remetente'),
        ),
        migrations.AlterField(
            model_name='physicalcontrol',
            name='action_type',
            field=models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Saída')], default='IN', max_length=3),
        ),
        migrations.AlterField(
            model_name='physicalcontrol',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='physicalcontrol',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='physicalcontrol',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='physicalcontrol',
            name='movement_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='physicalcontrol',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physicalcontrol',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='physicalcontrol',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='physicalcontrol',
            name='responsible_person',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='physicalcontrol',
            name='tracking_code',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
