# Generated by Django 5.0.1 on 2025-12-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_physicalcontrol_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalcontrol',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='physicalcontrol',
            name='product',
            field=models.CharField(max_length=255, verbose_name='Produto/Peça'),
        ),
    ]
