# Generated by Django 5.0.1 on 2025-12-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_physicalcontrol_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalcontrol',
            name='action_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Finalidade'),
        ),
    ]
