# Generated by Django 5.0.1 on 2025-12-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_location_alter_physicalcontrol_action_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='physicalcontrol',
            options={'verbose_name': 'Controle Físico', 'verbose_name_plural': 'Controles Físicos'},
        ),
        migrations.AlterField(
            model_name='location',
            name='authorized_personnel',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='physicalcontrol',
            name='product',
            field=models.CharField(max_length=255),
        ),
    ]
