# Generated by Django 5.0.1 on 2025-12-25 20:35

import django.db.models.deletion
import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_physicalcontrol_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalControlAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=inventory.models.upload_to_nf_folder)),
                ('attachment_type', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('physical_control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='inventory.physicalcontrol')),
            ],
        ),
    ]
