# Generated by Django 5.0.1 on 2025-12-21 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('revision', models.CharField(default='00', max_length=10, verbose_name='Revisão')),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('IN_REVIEW', 'Em Revisão'), ('APPROVED', 'Aprovado'), ('OBSOLETE', 'Obsoleto')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('approval_date', models.DateField(blank=True, null=True, verbose_name='Data de Aprovação')),
                ('file_url', models.URLField(blank=True, null=True, verbose_name='URL do Arquivo')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_drawings', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por')),
            ],
            options={
                'verbose_name': 'Desenho',
                'verbose_name_plural': 'Desenhos',
            },
        ),
    ]
