# Generated by Django 5.0.1 on 2025-12-26 01:43

import django.db.models.deletion
import django.utils.timezone
import physical_control.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('responsibles', models.ManyToManyField(related_name='managed_locations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_id', models.CharField(editable=False, max_length=25, unique=True)),
                ('nf_number', models.CharField(max_length=50)),
                ('receipt_date', models.DateField(default=django.utils.timezone.now)),
                ('sender', models.CharField(max_length=255)),
                ('nf_notes', models.TextField(blank=True, null=True)),
                ('nf_file', models.FileField(blank=True, null=True, upload_to=physical_control.models.get_nf_upload_path)),
                ('product', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('item_notes', models.TextField(blank=True, null=True)),
                ('photo_top', models.ImageField(blank=True, null=True, upload_to=physical_control.models.get_photo_upload_path)),
                ('photo_front', models.ImageField(blank=True, null=True, upload_to=physical_control.models.get_photo_upload_path)),
                ('photo_side', models.ImageField(blank=True, null=True, upload_to=physical_control.models.get_photo_upload_path)),
                ('photo_iso', models.ImageField(blank=True, null=True, upload_to=physical_control.models.get_photo_upload_path)),
                ('movement_history', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='physical_control.location')),
            ],
        ),
    ]
