# Generated by Django 5.0.1 on 2025-12-26 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physical_control', '0002_physicalcontrol_physical_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemProcessing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_id', models.CharField(max_length=25)),
                ('nf_number', models.CharField(max_length=50)),
                ('sender', models.CharField(max_length=255)),
                ('reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Motivo do Envio')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('status', models.CharField(default='Pendente', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processing', to='physical_control.physicalcontrol')),
            ],
        ),
    ]
