# Generated by Django 5.0.1 on 2025-12-26 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physical_control', '0003_itemprocessing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemprocessing',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemprocessing',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
