# Generated by Django 5.0.1 on 2025-12-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physical_control', '0004_alter_itemprocessing_observation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='physical_structure',
            field=models.JSONField(blank=True, default=list, help_text='Lista de armários cadastrados'),
        ),
    ]
