# Generated by Django 5.0.1 on 2025-12-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physical_control', '0005_location_physical_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalcontrol',
            name='customer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='physical_structure',
            field=models.JSONField(blank=True, default=list, help_text="Estrutura de armários: [{'name': str, 'rows': int, 'cols': int}]"),
        ),
    ]
